name: AutoTest

on:
  push:
    branches:
      - branchAutoTest
  pull_request:
    branches:
      - branchAutoTest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: AutoTest
      run: |
        ./configure
        make
        make check
