name: BuildingDebianPackage

on:
  push:
    branches:
      - branchAutoPackage
  pull_request:
    branches:
      - branchAutoPackage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build deb package
      run: |
        autoreconf --install
        ./configure --prefix=/
        make install DESTDIR=$(pwd)
        dpkg-deb --build deb
