name: Docker Compile and Push

on:
  push:
    branches:
      - branchHTTPserver
  pull_request:
    branches:
      - branchHTTPserver

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and configure project
      run: |
        autoreconf -i
        ./configure
        make

    - name: Log in to DockerHub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin

    - name: Build and push Docker image
      run: make docker-push

    - name: Run Docker container
      run: |
        docker run -d --name http_servere -p 8081:8081 ${{ secrets.DOCKER_USERNAME }}/http_server_image:latest
        docker ps
