name: BuildingTarball

on:
  push:
    branches:
      - branchAutoMake
  pull_request:
    branches:
      - branchAutoMake

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build with Automake
      run: |
        ./configure
        make
        make dist
